SET SEARCH_PATH = "PUBLIC";

DROP TABLE IF EXISTS PUBLIC.ENTITY_BASE;

CREATE TABLE PUBLIC.ENTITY_BASE (
    ID              BIGINT 		NOT NULL,
    STATUS          BOOLEAN     NULL DEFAULT TRUE,
    CREATED_AT      TIMESTAMP   NULL DEFAULT now(),
    UPDATED_AT      TIMESTAMP   NULL DEFAULT now(),

    CONSTRAINT ENTITY_BASE_PK PRIMARY KEY (ID)
);
