server:
  port: ${PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: service-client
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:admin}:${MONGO_PASSWORD:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/client_db?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: ${LB_EUREKA:http://localhost:8761}/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
