server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 2
    registry-fetch-interval-seconds: 2
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"